FROM php:8.2-fpm

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libpq-dev \
    libzip-dev \
    zip \
    unzip \
    git \
    libxml2-dev \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libonig-dev \
    redis-server \
    mariadb-client \
    mariadb-common \
    nginx

# Install PHP extensions
RUN docker-php-ext-install pdo pdo_mysql zip exif pcntl soap

# Install Composer globally
COPY --from=composer:2.0 /usr/bin/composer /usr/bin/composer

# Set working directory
WORKDIR /var/www/html

COPY default.conf info.php index.php .

# Copy Nginx config
COPY default.conf /etc/nginx/conf.d/default.conf

RUN chown -R www-data:www-data /var/www/html

# Expose port 80 (default PHP-FPM port)
EXPOSE 80
EXPOSE 8080

# Start PHP-FPM server
CMD ["sh", "-c", "php-fpm -D && nginx -g 'daemon off;'"]